tilte: Dr. Veena G 
logo: docs/assets/Dr.Veena G[1] (1).jpg
description: Assistant Professor | Statistician | Data Analyst

theme: jekyll-theme-minimal
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"

