tilte:  Dr. Veena G | Statistician & Educator
logo: docs/assets/Dr.Veena G[1] (1).jpg
description: Assistant Professor | Statistician | Data Analyst

theme: Architect
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"

