tilte: Dr. Veena G 
logo: docs/assets/Dr.Veena G[1] (1).jpg
description: Assistant Professor | Statistician | Data Analyst
Welcome to my professional webpage. Here, you’ll find an overview of my academic background, professional experience, and domain expertise. You can also explore my blog posts and projects by navigating through the sidebar or top menu.

theme: jekyll-theme-minimal

